name: "Build Chrome extension"
description: "Builds the chrome extension into a ZIP"
runs:
  using: "composite"
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install packages
      run: bun i
      shell: bash

    - name: Build extension
      run: bun run build
      working-directory: apps/solomon/chrome-extension
      shell: bash

    - name: Pack extension
      working-directory: apps/solomon/chrome-extension/dist
      run: zip -r extension-${{ github.sha }}.zip *
      shell: bash

    - name: Upload extension archive
      uses: actions/upload-artifact@v3
      with:
        name: extension-${{ github.sha }}
        path: apps/solomon/chrome-extension/dist/extension-${{ github.sha }}.zip
