name = "web"
compatibility_date = "2024-03-29"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "solomon-ai-chrome-extension-db"
database_id = "b9c11b9f-1e48-4a46-87c2-ff4b50dec0f7"


[[unsafe.bindings]]
name = "RATELIMITER"
type = "ratelimit"
namespace_id = "1001"

# 25 requests per 10 seconds
simple = { limit = 25, period = 10 }

[placement]
mode = "smart"