// Generated by Wrangler on Thu May 09 2024 00:06:48 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types -e production`

interface Env {
	production: KVNamespace;
	ENVIRONMENT: "production";
	OPENAI_API_KEY: "";
	GATEWAY_URL: "https://gateway.ai.cloudflare.com/v1/de345701e5dc7e14d3c079da3e637448/solomon-ai-gateway-production";
	OPEN_AI_MODEL: "gpt-3.5-turbo";
	bucket: R2Bucket;
	db: D1Database;
	AI: unknown;
}
